/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZetaConnector } from "./ZetaConnector";
export type { ZetaReceiver } from "./ZetaReceiver";
export type { ZetaTokenConsumer } from "./ZetaTokenConsumer";
