/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export declare namespace ZetaInterfaces {
  export type ZetaMessageStruct = {
    zetaTxSenderAddress: BytesLike;
    sourceChainId: BigNumberish;
    destinationAddress: string;
    zetaValueAndGas: BigNumberish;
    message: BytesLike;
  };

  export type ZetaMessageStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    string
  ] & {
    zetaTxSenderAddress: string;
    sourceChainId: BigNumber;
    destinationAddress: string;
    zetaValueAndGas: BigNumber;
    message: string;
  };

  export type ZetaRevertStruct = {
    zetaTxSenderAddress: string;
    sourceChainId: BigNumberish;
    destinationAddress: BytesLike;
    destinationChainId: BigNumberish;
    zetaValueAndGas: BigNumberish;
    message: BytesLike;
  };

  export type ZetaRevertStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    zetaTxSenderAddress: string;
    sourceChainId: BigNumber;
    destinationAddress: string;
    destinationChainId: BigNumber;
    zetaValueAndGas: BigNumber;
    message: string;
  };
}

export interface ZetaReceiverInterface extends utils.Interface {
  functions: {
    "onZetaMessage((bytes,uint256,address,uint256,bytes))": FunctionFragment;
    "onZetaRevert((address,uint256,bytes,uint256,uint256,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "onZetaMessage" | "onZetaRevert"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "onZetaMessage",
    values: [ZetaInterfaces.ZetaMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "onZetaRevert",
    values: [ZetaInterfaces.ZetaRevertStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "onZetaMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onZetaRevert",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ZetaReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ZetaReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    onZetaMessage(
      zetaMessage: ZetaInterfaces.ZetaMessageStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onZetaRevert(
      zetaRevert: ZetaInterfaces.ZetaRevertStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  onZetaMessage(
    zetaMessage: ZetaInterfaces.ZetaMessageStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onZetaRevert(
    zetaRevert: ZetaInterfaces.ZetaRevertStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    onZetaMessage(
      zetaMessage: ZetaInterfaces.ZetaMessageStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    onZetaRevert(
      zetaRevert: ZetaInterfaces.ZetaRevertStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    onZetaMessage(
      zetaMessage: ZetaInterfaces.ZetaMessageStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onZetaRevert(
      zetaRevert: ZetaInterfaces.ZetaRevertStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onZetaMessage(
      zetaMessage: ZetaInterfaces.ZetaMessageStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onZetaRevert(
      zetaRevert: ZetaInterfaces.ZetaRevertStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
