/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { IWETH } from "./IWETH";
