/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Burnable__factory } from "./ERC20Burnable__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
