/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ImmutableCreate2Factory__factory } from "./ImmutableCreate2Factory__factory";
export { Ownable__factory } from "./Ownable__factory";
