/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZetaTokenConsumerUniV2 } from "./ZetaTokenConsumerUniV2";
export type { ZetaTokenConsumerUniV2Errors } from "./ZetaTokenConsumerUniV2Errors";
