/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ZetaTokenConsumerUniV2__factory } from "./ZetaTokenConsumerUniV2__factory";
export { ZetaTokenConsumerUniV2Errors__factory } from "./ZetaTokenConsumerUniV2Errors__factory";
