name: 'Build Docker Images'
description: 'Builds Docker images and pushes them to ECR and GHCR'
inputs:
  DOCKER_FILENAME:  
    description: 'Name of the docker file to use for the build'
    required: true
  REPOSITORY_NAME:  
    description: 'Name of the Repository'
    required: true
  IMAGE_TAG:  
    description: 'Image Tag'
    required: true
  GHCR_USERNAME: 
    description: 'Username for GitHub Container Registry'
    required: true
  GHCR_TOKEN:
    description: 'Token for GitHub Container Registry'
    required: true

runs:
  using: "composite"

  steps:
    - name: Set Environment Variables"
      run: |
        echo "DOCKER_FILENAME=${{ inputs.DOCKER_FILENAME }}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${{ inputs.REPOSITORY_NAME }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV
        echo "GHCR_USERNAME=${{ inputs.GHCR_USERNAME }}" >> $GITHUB_ENV
        echo "GHCR_TOKEN=${{ inputs.GHCR_TOKEN }}" >> $GITHUB_ENV
      shell: bash

    - name: Log in to the GitHub Container Registry 
      id: login-ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io 
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ env.GHCR_TOKEN }}

    - name: Build, tag, and push images
      shell: bash
      env:
        GHCR_REGISTRY: ghcr.io/zeta-chain
      run: |
        docker build -f $DOCKER_FILENAME -t $GHCR_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG .
        docker push $GHCR_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG
